# Generated by Django 4.1.6 on 2023-03-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenimg',
            name='emimgpath',
        ),
    ]
