# Generated by Django 4.1.6 on 2023-03-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0002_remove_authenimg_emimgpath'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenimg',
            options={'managed': False},
        ),
    ]
