# Generated by Django 4.1.6 on 2023-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0002_authenimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GivepawsAuthenimage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'givepaws_authenimage',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Hcapprovedocument',
        ),
        migrations.AlterField(
            model_name='authenimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/authen'),
        ),
    ]
