# Generated by Django 4.1.6 on 2023-03-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0003_alter_authenimg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenimg',
            options={'managed': True},
        ),
    ]
