# Generated by Django 4.1.6 on 2023-03-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0004_authencheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipttype',
        ),
    ]
