# Generated by Django 4.1.6 on 2023-03-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0004_alter_authenimg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenimg',
            options={'managed': False},
        ),
    ]
