# Generated by Django 4.1.6 on 2023-03-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0005_alter_authenimg_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('authenid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='givepaws.authen')),
            ],
        ),
    ]
