# Generated by Django 4.1.6 on 2023-03-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0005_delete_receipttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img/card')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='givepaws.card')),
            ],
        ),
    ]
