# Generated by Django 4.1.6 on 2023-03-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0006_authenimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenimage',
            options={'managed': False},
        ),
    ]
