# Generated by Django 4.1.6 on 2023-03-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0007_alter_authenimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenimage',
            options={'managed': True},
        ),
    ]
