# Generated by Django 4.1.6 on 2023-03-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givepaws', '0008_alter_authenimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenimage',
            options={},
        ),
    ]
